<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/danielzhu/Documents/dszhudes/static/mottledPot.glb --types
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group } from "three";
  import {
    T,
    type Props,
    type Events,
    type Slots,
    forwardEventHandlers,
  } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
  import Loading from "./loading.svelte";

  type $$Props = Props<THREE.Group>;
  type $$Events = Events<THREE.Group>;
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

  export const ref = new Group();

  type GLTFResult = {
    nodes: {
      mesh_0: THREE.Mesh;
    };
    materials: {};
  };

  const gltf = useGltf<GLTFResult>("/mottledPot.glb");
  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback">
      <Loading />
    </slot>
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.mesh_0.geometry}
      material={gltf.nodes.mesh_0.material}
      scale={5}
      position={[0, -1, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
